# Generated by Django 3.2.7 on 2022-06-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='photo1',
            field=models.ImageField(blank=True, default='/interior1_sample.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo2',
            field=models.ImageField(blank=True, default='/interior2_sample.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo3',
            field=models.ImageField(blank=True, default='/interior3_sample.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo4',
            field=models.ImageField(blank=True, default='/interior4_sample.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='plot_area',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Plot Area(metres square feet)'),
        ),
    ]
